name: Frontend build
on:
  push:
    branches: ["main"]
    paths:
      - src/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: versioning
      id: versioning
      uses: paulhatch/semantic-version@v5.0.2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-${increment}"
        bump_each_commit: true
        search_commit_body: true
        user_format_type: "csv"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
       docker build . --tag ghcr.io/mcb2001/oc6-404:${{ steps.versioning.outputs.version }}
       docker push ghcr.io/mcb2001/oc6-404:${{ steps.versioning.outputs.version }}